
package it.water.connectors.jobscheduler.service.rest;

import it.water.connectors.jobscheduler.api.*;
import it.water.connectors.jobscheduler.api.rest.*;
import it.water.connectors.jobscheduler.model.*;

import it.water.core.api.service.rest.FrameworkRestController;
import it.water.core.interceptors.annotations.*;


import lombok.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * @Generated by Water Generator
 * Rest Api Class for JobScheduler entity.
 *
 */
@FrameworkRestController(referredRestApi = JobSchedulerRestApi.class)
public class JobSchedulerRestControllerImpl  implements JobSchedulerRestApi {
    @SuppressWarnings("java:S1068") //still mantain the variable even if not used
    private static Logger log = LoggerFactory.getLogger(JobSchedulerRestControllerImpl.class.getName());
    
    @Inject
    @Setter
    private JobSchedulerApi jobSchedulerApi;
    //All CRUD methods are already exposed by JobSchedulerRestApi interface with JAXRS Annotatiosn
    //if you need to check which methods are exposed please go to it.water.connectors.jobscheduler.api.rest.JobScheduler

    //ATTENTION: use always JobSchedulerApi in order to ensure the user is requesting operations has the right privileges to do it

}
