package it.water.connectors.jobscheduler.api;

import it.water.core.api.service.BaseSystemApi;

/**
 *
 * @Generated by Water Generator
 * This interface defines the internally exposed methods allows interaction with them bypassing permission system.
 *
 */
public interface JobSchedulerSystemApi extends BaseSystemApi {

    /**
     * This method adds a job to be scheduled
     * @param job Job to be scheduled
     */
    void addJob(WaterJob job);

    /**
     * This method removes a job from being scheduled
     * @param job Job to be removed
     */
    void deleteJob(WaterJob job);

    /**
     * This method updates the scheduling of a given job
     * @param job Job to be updated
     */
    void updateJob(WaterJob job);

}