package it.water.connectors.jobscheduler.api.rest;

import io.swagger.annotations.Api;
import it.water.core.api.service.rest.FrameworkRestApi;
import it.water.core.api.service.rest.RestApi;

import javax.ws.rs.Path;
import javax.ws.rs.core.MediaType;

/**
 * @Generated by Water Generator
 * Rest Api Interface for JobScheduler entity.
 * This interfaces exposes all CRUD methods with default JAXRS annotations.
 *
 */
@Path("/jobSchedulers")
@Api(produces = MediaType.APPLICATION_JSON, tags = "JobScheduler API")
@FrameworkRestApi
public interface JobSchedulerRestApi extends RestApi {

}
