package it.water.connectors.jobscheduler.api.rest;

import it.water.connectors.jobscheduler.model.*;
import it.water.core.api.model.PaginableResult;
import it.water.core.api.service.rest.FrameworkRestApi;
import it.water.core.api.service.rest.RestApi;
import it.water.service.rest.api.security.LoggedIn;

import com.fasterxml.jackson.annotation.JsonView;
import it.water.core.api.service.rest.WaterJsonView;
import io.swagger.annotations.*;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;

/**
 * @Generated by Water Generator
 * Rest Api Interface for JobScheduler entity.
 * This interfaces exposes all CRUD methods with default JAXRS annotations.
 *
 */
@Path("/jobSchedulers")
@Api(produces = MediaType.APPLICATION_JSON, tags = "JobScheduler API")
@FrameworkRestApi
public interface JobSchedulerRestApi extends RestApi {

}
