package it.water.connectors.jobscheduler;

import it.water.core.api.bundle.Runtime;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.api.service.Service;
import it.water.core.interceptors.annotations.Inject;
import it.water.core.testing.utils.junit.WaterTestExtension;

import it.water.connectors.jobscheduler.api.*;

import lombok.Setter;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;

/**
 * @Generated by Water Generator
 * Test class for JobScheduler Services.
 */
@ExtendWith(WaterTestExtension.class)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class JobSchedulerApiTest implements Service {

    @Inject
    @Setter
    private ComponentRegistry componentRegistry;

    @Inject
    @Setter
    private JobSchedulerApi jobSchedulerApi;

    @Inject
    @Setter
    private Runtime runtime;

    /**
     * Testing basic injection of components for JobScheduler service.
     */
    @Test
    @Order(1)
    void componentsInstantiatedCorrectly() {
        this.jobSchedulerApi = this.componentRegistry.findComponent(JobSchedulerApi.class, null);
        Assertions.assertNotNull(this.jobSchedulerApi);
        Assertions.assertNotNull(this.componentRegistry.findComponent(JobSchedulerSystemApi.class, null));
    }

    @Test
    @Order(2)
    void repositoryInstantiatedCorrectly() {
        Assertions.assertNotNull(this.componentRegistry.findComponent(JobSchedulerRepository.class, null));
    }

}
