package it.water.connectors.jobscheduler.service;

import it.water.connectors.jobscheduler.api.JobSchedulerApi;
import it.water.connectors.jobscheduler.api.JobSchedulerSystemApi;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.core.service.BaseServiceImpl;
import lombok.Getter;
import lombok.Setter;


/**
 * @Generated by Water Generator
 * Service Api Class for JobScheduler entity.
 *
 */
@FrameworkComponent
public class JobSchedulerServiceImpl extends BaseServiceImpl implements JobSchedulerApi {

    @Inject
    @Getter
    @Setter
    private JobSchedulerSystemApi systemService;

    @Inject
    @Getter
    @Setter
    private ComponentRegistry componentRegistry;

    public JobSchedulerServiceImpl() {
    }

    //use getLog to retrieve Logger instance automatically instantiated for this class
}
