package it.water.connectors.jobscheduler.service;

import it.water.connectors.jobscheduler.api.JobSchedulerRepository;
import it.water.connectors.jobscheduler.api.JobSchedulerSystemApi;
import it.water.connectors.jobscheduler.api.WaterJob;
import it.water.connectors.jobscheduler.model.JobSchedulerConstants;
import it.water.connectors.zookeeper.api.ZookeeperConnectorSystemApi;
import it.water.core.api.bundle.ApplicationProperties;
import it.water.core.api.interceptors.OnActivate;
import it.water.core.api.interceptors.OnDeactivate;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.core.service.BaseSystemServiceImpl;
import lombok.Setter;
import org.apache.curator.framework.recipes.leader.LeaderLatchListener;
import org.quartz.*;
import org.quartz.impl.StdSchedulerFactory;

import java.io.InputStream;
import java.text.ParseException;
import java.util.*;

import static org.quartz.CronScheduleBuilder.cronSchedule;
import static org.quartz.TriggerBuilder.newTrigger;

/**
 * @Generated by Water Generator
 * System Service Api Class for JobScheduler.
 * Implements Quartz-based job scheduling with Zookeeper cluster leadership support.
 */
@FrameworkComponent
public class JobSchedulerSystemServiceImpl extends BaseSystemServiceImpl implements JobSchedulerSystemApi {

    private Properties quartzProps;
    private Properties jobschedulerProps;
    private Scheduler scheduler;

    @Inject
    @Setter
    private ZookeeperConnectorSystemApi zookeeperConnectorSystemApi;

    @Inject
    @Setter
    private JobSchedulerRepository repository;

    @Inject
    @Setter
    private JobSchedulerLeadershipRegistrar jobSchedulerLeadershipRegistrar;

    @OnActivate
    public void onActivate(ApplicationProperties applicationProperties) {
        try {
            loadProperties(applicationProperties);
            // Create Quartz tables if they don't exist
            this.repository.createQuartzTableIfNotExists(
                    jobschedulerProps.getProperty(JobSchedulerConstants.JOB_SCHEDULER_INIT_SCRIPT, null));
            // Get the scheduler
            getLog().info("Get scheduler");
            StdSchedulerFactory stdSchedulerFactory = getSchedulerFactory();
            scheduler = stdSchedulerFactory.getScheduler();
            if (zookeeperConnectorSystemApi.isLeader(jobSchedulerLeadershipRegistrar.getLeadershipPath())) {
                getLog().info("Scheduler is on zk leader, start");
                scheduler.start();
            }
            addLeaderLatchListener();
        } catch (SchedulerException e) {
            getLog().error(e.getMessage(), e);
        }
    }

    @OnDeactivate
    public void onDeactivate() {
        try {
            if (scheduler != null)
                scheduler.shutdown();
        } catch (SchedulerException e) {
            getLog().error(e.getMessage(), e);
        }
    }

    @Override
    public void addJob(WaterJob job) {
        JobDetail jobDetail = job.getJobDetail();
        if (jobDetail == null) {
            String errorMsg = "Could not add job: jobDetail was null";
            getLog().error(errorMsg);
            throw new RuntimeException(errorMsg);
        }
        JobKey jobKey = jobDetail.getKey();
        getLog().info("Adding job {} to scheduler", jobKey);
        try {
            if (!scheduler.checkExists(jobKey)) {
                scheduler.addJob(jobDetail, false);
                if (job.isActive()) {
                    schedule(job);
                }
            } else
                getLog().warn("Job {} already exists, it has not been added", jobKey);
        } catch (ParseException | SchedulerException e) {
            getLog().error("Could not schedule job {}: {}", new Object[]{jobKey, e.getMessage()});
            throw new RuntimeException(e);
        }
    }

    @Override
    public void deleteJob(WaterJob job) {
        JobKey jobKey = job.getJobKey();
        if (jobKey == null) {
            String errorMsg = "Could not delete job: jobKey was null";
            getLog().error(errorMsg);
            throw new RuntimeException(errorMsg);
        }
        getLog().info("Removing job {} from scheduler", jobKey);
        try {
            if (!scheduler.checkExists(jobKey))
                getLog().warn("Job {} does not exist", jobKey);
            else
                deleteJobFromScheduler(job);
        } catch (SchedulerException e) {
            getLog().error("Job {} has not been removed: {}", new Object[]{jobKey, e.getMessage()});
            throw new RuntimeException(e);
        }
    }

    @Override
    public void updateJob(WaterJob job) {
        JobDetail jobDetail = job.getJobDetail();
        if (jobDetail == null) {
            String errorMsg = "Could not update job: jobDetail was null";
            getLog().error(errorMsg);
            throw new RuntimeException(errorMsg);
        }
        JobKey jobKey = job.getJobKey();
        getLog().info("Updating job {} to scheduler", jobKey);
        try {
            if (scheduler.checkExists(jobKey)) {
                scheduler.addJob(jobDetail, true);
                if (job.isActive()) {
                    schedule(job);
                } else {
                    unschedule(job);
                }
            } else
                getLog().warn("Job does not exist, it has been neither updated nor scheduled");
        } catch (ParseException | SchedulerException e) {
            getLog().error("Job {} has not been updated: {}", new Object[]{jobKey, e.getMessage()});
            throw new RuntimeException(e);
        }
    }

    /**
     * Adds a LeaderLatchListener for scheduler start/standby transitions.
     */
    private void addLeaderLatchListener() {
        String leadershipPath = jobSchedulerLeadershipRegistrar.getLeadershipPath();
        zookeeperConnectorSystemApi.addListener(new LeaderLatchListener() {

            @Override
            public void isLeader() {
                getLog().info("This node has become a zk leader, start scheduler");
                try {
                    scheduler.start();
                } catch (SchedulerException e) {
                    getLog().error("Scheduler has not been started: {}", e.getMessage());
                }
            }

            @Override
            public void notLeader() {
                getLog().info("This node is not a zk leader anymore, standby scheduler");
                try {
                    scheduler.standby();
                } catch (SchedulerException e) {
                    getLog().error("Scheduler has not been paused: {}", e.getMessage());
                }
            }

        }, leadershipPath);
    }

    private void loadProperties(ApplicationProperties applicationProperties) {
        if (quartzProps == null) {
            quartzProps = new Properties();
            jobschedulerProps = new Properties();
            // Load properties from classpath config file
            try (InputStream is = this.getClass().getClassLoader()
                    .getResourceAsStream("it.water.connectors.jobscheduler.cfg")) {
                if (is != null) {
                    Properties allProps = new Properties();
                    allProps.load(is);
                    for (String key : allProps.stringPropertyNames()) {
                        String value = allProps.getProperty(key);
                        if (key.startsWith(JobSchedulerConstants.QUARTZ_PROPERTY_PREFIX)) {
                            quartzProps.put(key, value);
                        } else {
                            jobschedulerProps.put(key, value);
                        }
                    }
                }
            } catch (Exception e) {
                getLog().warn("Could not load it.water.connectors.jobscheduler.cfg from classpath: {}", e.getMessage());
            }
            // Also check ApplicationProperties for any overrides
            String initScript = applicationProperties.getPropertyOrDefault(
                    JobSchedulerConstants.JOB_SCHEDULER_INIT_SCRIPT, null);
            if (initScript != null) {
                jobschedulerProps.put(JobSchedulerConstants.JOB_SCHEDULER_INIT_SCRIPT, initScript);
            }
            getLog().debug("Loaded properties for JobScheduler: {}", quartzProps);
        }
    }

    private void schedule(WaterJob job) throws ParseException, SchedulerException {
        JobKey jobKey = job.getJobKey();
        getLog().info("Scheduling job {}", jobKey);
        String cronExpression = job.getCronExpression();
        CronExpression.validateExpression(cronExpression);
        TriggerKey triggerKey = new TriggerKey(jobKey.getName(), jobKey.getGroup());
        TriggerBuilder triggerBuilder;
        Trigger oldTrigger = null;
        if (scheduler.checkExists(triggerKey)) {
            oldTrigger = scheduler.getTrigger(triggerKey);
            triggerBuilder = oldTrigger.getTriggerBuilder();
        } else {
            triggerBuilder = newTrigger().withIdentity(triggerKey);
        }
        Trigger trigger = triggerBuilder
                .withSchedule(cronSchedule(cronExpression).withMisfireHandlingInstructionFireAndProceed())
                .forJob(jobKey)
                .build();
        if (oldTrigger == null)
            scheduler.scheduleJob(trigger);
        else
            scheduler.rescheduleJob(triggerKey, trigger);
    }

    private void deleteJobFromScheduler(WaterJob job) throws SchedulerException {
        JobKey jobKey = job.getJobKey();
        getLog().info("Unscheduling job {}", jobKey);
        if (scheduler.checkExists(jobKey)) {
            scheduler.deleteJob(jobKey);
            getLog().info("Job {} has been unscheduled successfully", jobKey);
        } else
            getLog().info("Job {} has not been scheduled yet", jobKey);
    }

    private void unschedule(WaterJob job) throws SchedulerException {
        JobKey jobKey = job.getJobKey();
        TriggerKey triggerKey = new TriggerKey(jobKey.getName(), jobKey.getGroup());
        if (scheduler.checkExists(triggerKey)) {
            getLog().info("Unscheduling job {}", jobKey);
            scheduler.unscheduleJob(triggerKey);
        }
    }

    protected StdSchedulerFactory getSchedulerFactory() throws SchedulerException {
        return new StdSchedulerFactory(quartzProps);
    }
}
